-- KEPR Inventory: run this entire file in Supabase SQL Editor.
-- It creates the schema, secure atomic RPCs, views, RLS, and authenticated access.

create table if not exists public.inventory_products (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0),
  unit text not null check (unit in ('Pcs','Liters','Kg','Packets','Bottles')),
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  reorder_level numeric(14,3) not null default 0 check (reorder_level >= 0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists inventory_products_name_unique
  on public.inventory_products (lower(trim(name)));

create table if not exists public.inventory_apartments (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0),
  contact text not null default '',
  created_at timestamptz not null default now()
);
create unique index if not exists inventory_apartments_name_unique
  on public.inventory_apartments (lower(trim(name)));

create table if not exists public.inventory_stock_levels (
  id bigint generated by default as identity primary key,
  location_type text not null check (location_type in ('warehouse','apartment')),
  apartment_id bigint references public.inventory_apartments(id) on delete cascade,
  product_id bigint not null references public.inventory_products(id) on delete restrict,
  quantity numeric(14,3) not null default 0 check (quantity >= 0),
  monthly_use numeric(14,3) not null default 0 check (monthly_use >= 0),
  audited_at date,
  updated_at timestamptz not null default now(),
  check (
    (location_type = 'warehouse' and apartment_id is null) or
    (location_type = 'apartment' and apartment_id is not null)
  ),
  unique nulls not distinct (location_type, apartment_id, product_id)
);

create table if not exists public.inventory_stock_movements (
  id bigint generated by default as identity primary key,
  reference text not null,
  movement_type text not null check (movement_type in ('receipt','transfer','adjustment')),
  product_id bigint not null references public.inventory_products(id) on delete restrict,
  apartment_id bigint references public.inventory_apartments(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  movement_date date not null default current_date,
  note text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists inventory_movements_reference_idx
  on public.inventory_stock_movements(reference);
create index if not exists inventory_movements_date_idx
  on public.inventory_stock_movements(movement_date desc);

create or replace view public.inventory_products_view
with (security_invoker = true) as
select p.*, coalesce(s.quantity, 0)::double precision as quantity
from public.inventory_products p
left join public.inventory_stock_levels s
  on s.product_id = p.id and s.location_type = 'warehouse'
order by lower(p.name);

create or replace view public.inventory_apartments_view
with (security_invoker = true) as
select a.id, a.name, a.contact, a.created_at,
       count(s.product_id)::integer as item_count,
       coalesce(sum(s.quantity * p.unit_price), 0)::double precision as stock_value
from public.inventory_apartments a
left join public.inventory_stock_levels s
  on s.apartment_id = a.id and s.location_type = 'apartment'
left join public.inventory_products p on p.id = s.product_id
group by a.id
order by lower(a.name);

create or replace view public.inventory_apartment_stock_view
with (security_invoker = true) as
select s.apartment_id, a.name as apartment_name, s.product_id,
       p.name as product_name, p.unit,
       s.quantity::double precision as quantity,
       s.monthly_use::double precision as monthly_use,
       p.unit_price::double precision as unit_price
from public.inventory_stock_levels s
join public.inventory_products p on p.id = s.product_id
join public.inventory_apartments a on a.id = s.apartment_id
where s.location_type = 'apartment'
order by lower(p.name);

create or replace view public.inventory_transfers_view
with (security_invoker = true) as
select m.reference, m.movement_date::text, a.name as apartment,
       count(*)::integer as line_count,
       sum(m.quantity)::double precision as total_quantity,
       sum(m.quantity * m.unit_price)::double precision as total_value,
       max(m.id) as sort_id
from public.inventory_stock_movements m
join public.inventory_apartments a on a.id = m.apartment_id
where m.movement_type = 'transfer'
group by m.reference, m.movement_date, a.name
order by max(m.id) desc;

create or replace function public.inventory_save_product(
  p_id bigint, p_name text, p_unit text, p_quantity numeric,
  p_unit_price numeric, p_reorder_level numeric, p_notes text
) returns bigint
language plpgsql security invoker set search_path = public as $$
declare v_id bigint;
begin
  if p_quantity < 0 then raise exception 'Quantity cannot be negative'; end if;
  if p_id is null then
    insert into inventory_products(name, unit, unit_price, reorder_level, notes)
    values(trim(p_name), p_unit, p_unit_price, p_reorder_level, coalesce(p_notes,''))
    returning id into v_id;
    insert into inventory_stock_levels(location_type, product_id, quantity)
    values('warehouse', v_id, p_quantity);
  else
    v_id := p_id;
    update inventory_products set name=trim(p_name), unit=p_unit,
      unit_price=p_unit_price, reorder_level=p_reorder_level,
      notes=coalesce(p_notes,''), updated_at=now() where id=p_id;
    update inventory_stock_levels set quantity=p_quantity, updated_at=now()
      where location_type='warehouse' and product_id=p_id;
  end if;
  return v_id;
end $$;

create or replace function public.inventory_transfer_stock(
  p_apartment_id bigint, p_movement_date date, p_lines jsonb
) returns text
language plpgsql security invoker set search_path = public as $$
declare
  v_line jsonb; v_product_id bigint; v_quantity numeric;
  v_available numeric; v_price numeric; v_name text;
  v_reference text := 'TR-' || to_char(coalesce(p_movement_date,current_date),'YYYYMMDD')
    || '-' || upper(substr(md5(gen_random_uuid()::text),1,6));
begin
  if jsonb_array_length(p_lines) = 0 then raise exception 'Add at least one item'; end if;
  perform 1 from inventory_apartments where id=p_apartment_id;
  if not found then raise exception 'Apartment not found'; end if;
  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_product_id := (v_line->>'product_id')::bigint;
    v_quantity := (v_line->>'quantity')::numeric;
    if v_quantity <= 0 then raise exception 'Quantity must be positive'; end if;
    select s.quantity, p.unit_price, p.name into v_available, v_price, v_name
      from inventory_stock_levels s join inventory_products p on p.id=s.product_id
      where s.location_type='warehouse' and s.product_id=v_product_id for update of s;
    if not found then raise exception 'Product not found'; end if;
    if v_available < v_quantity then
      raise exception '% has only % available', v_name, v_available;
    end if;
    update inventory_stock_levels set quantity=quantity-v_quantity, updated_at=now()
      where location_type='warehouse' and product_id=v_product_id;
    insert into inventory_stock_levels(location_type,apartment_id,product_id,quantity)
      values('apartment',p_apartment_id,v_product_id,v_quantity)
      on conflict(location_type,apartment_id,product_id)
      do update set quantity=inventory_stock_levels.quantity+excluded.quantity,updated_at=now();
    insert into inventory_stock_movements(reference,movement_type,product_id,
      apartment_id,quantity,unit_price,movement_date)
      values(v_reference,'transfer',v_product_id,p_apartment_id,v_quantity,
        v_price,coalesce(p_movement_date,current_date));
  end loop;
  return v_reference;
end $$;

alter table public.inventory_products enable row level security;
alter table public.inventory_apartments enable row level security;
alter table public.inventory_stock_levels enable row level security;
alter table public.inventory_stock_movements enable row level security;

drop policy if exists "inventory authenticated products" on public.inventory_products;
create policy "inventory authenticated products" on public.inventory_products
  for all to authenticated using (true) with check (true);
drop policy if exists "inventory authenticated apartments" on public.inventory_apartments;
create policy "inventory authenticated apartments" on public.inventory_apartments
  for all to authenticated using (true) with check (true);
drop policy if exists "inventory authenticated stock" on public.inventory_stock_levels;
create policy "inventory authenticated stock" on public.inventory_stock_levels
  for all to authenticated using (true) with check (true);
drop policy if exists "inventory authenticated movements" on public.inventory_stock_movements;
create policy "inventory authenticated movements" on public.inventory_stock_movements
  for all to authenticated using (true) with check (true);

grant select, insert, update, delete on public.inventory_products,
  public.inventory_apartments, public.inventory_stock_levels,
  public.inventory_stock_movements to authenticated;
grant select on public.inventory_products_view, public.inventory_apartments_view,
  public.inventory_apartment_stock_view, public.inventory_transfers_view to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.inventory_save_product(
  bigint,text,text,numeric,numeric,numeric,text) to authenticated;
grant execute on function public.inventory_transfer_stock(bigint,date,jsonb)
  to authenticated;
