-- Private invoice files mapped to fulfilled demand tickets.

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
  'inventory-invoices',
  'inventory-invoices',
  false,
  10485760,
  array['application/pdf','image/jpeg','image/png','image/webp']
)
on conflict(id) do update set
  public=false,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

create table if not exists public.inventory_invoices (
  id bigint generated by default as identity primary key,
  request_id bigint not null unique
    references public.inventory_requests(id) on delete restrict,
  invoice_number text not null check(length(trim(invoice_number))>0),
  invoice_date date not null,
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null check(size_bytes>0 and size_bytes<=10485760),
  uploaded_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists inventory_invoices_date_idx
  on public.inventory_invoices(invoice_date desc);

alter table public.inventory_invoices enable row level security;
drop policy if exists "invoice metadata by workflow role"
  on public.inventory_invoices;
create policy "invoice metadata by workflow role"
  on public.inventory_invoices for select to authenticated using (
    inventory_is_admin() or inventory_is_finance() or exists(
      select 1 from inventory_requests r
      where r.id=request_id and r.apartment_id=(
        select apartment_id from inventory_users where user_id=auth.uid()
      )
    )
  );

drop policy if exists "inventory admin uploads invoices" on storage.objects;
create policy "inventory admin uploads invoices"
  on storage.objects for insert to authenticated with check (
    bucket_id='inventory-invoices' and inventory_is_admin()
  );
drop policy if exists "workflow roles read invoices" on storage.objects;
create policy "workflow roles read invoices"
  on storage.objects for select to authenticated using (
    bucket_id='inventory-invoices' and (
      inventory_is_admin() or inventory_is_finance() or exists(
        select 1 from inventory_invoices i
        join inventory_requests r on r.id=i.request_id
        where i.storage_path=name and r.apartment_id=(
          select apartment_id from inventory_users where user_id=auth.uid()
        )
      )
    )
  );
drop policy if exists "inventory admin deletes failed invoice uploads"
  on storage.objects;
create policy "inventory admin deletes failed invoice uploads"
  on storage.objects for delete to authenticated using (
    bucket_id='inventory-invoices' and inventory_is_admin()
  );

create or replace view public.inventory_invoice_register_view
with (security_invoker=true) as
select i.id,i.request_id,r.reference request_reference,
  r.apartment_id,a.name apartment,i.invoice_number,
  i.invoice_date::text,i.storage_path,i.original_filename,
  i.mime_type,i.size_bytes,i.created_at::text
from inventory_invoices i
join inventory_requests r on r.id=i.request_id
join inventory_apartments a on a.id=r.apartment_id
order by i.invoice_date desc,i.id desc;

drop function if exists public.inventory_fulfill_request(bigint,text);

create or replace function public.inventory_fulfill_request(
  p_request_id bigint,
  p_invoice_number text,
  p_invoice_date date,
  p_storage_path text,
  p_original_filename text,
  p_mime_type text,
  p_size_bytes bigint
) returns text
language plpgsql security definer set search_path=public as $$
declare v_request inventory_requests%rowtype; v_line record;
  v_available numeric; v_reference text := 'TR-'||to_char(current_date,'YYYYMMDD')
    ||'-'||upper(substr(md5(gen_random_uuid()::text),1,6));
begin
  if not inventory_is_admin() then raise exception 'Inventory access required'; end if;
  if length(trim(coalesce(p_invoice_number,'')))=0 then
    raise exception 'Invoice number is required';
  end if;
  if p_invoice_date is null then raise exception 'Invoice date is required'; end if;
  if length(trim(coalesce(p_storage_path,'')))=0 then
    raise exception 'Invoice file is required';
  end if;
  if p_size_bytes<=0 or p_size_bytes>10485760 then
    raise exception 'Invoice file must be between 1 byte and 10 MB';
  end if;
  select * into v_request from inventory_requests where id=p_request_id for update;
  if v_request.status<>'finance_approved' then raise exception 'Finance approval required'; end if;
  for v_line in select rl.*,p.name,p.unit_price from inventory_request_lines rl
    join inventory_products p on p.id=rl.product_id
    where rl.request_id=p_request_id loop
    select quantity into v_available from inventory_stock_levels
      where location_type='warehouse' and product_id=v_line.product_id for update;
    if coalesce(v_available,0)<v_line.quantity then
      raise exception '% has only % available',v_line.name,coalesce(v_available,0);
    end if;
    update inventory_stock_levels set quantity=quantity-v_line.quantity,updated_at=now()
      where location_type='warehouse' and product_id=v_line.product_id;
    insert into inventory_stock_levels(location_type,apartment_id,product_id,quantity)
      values('apartment',v_request.apartment_id,v_line.product_id,v_line.quantity)
      on conflict(location_type,apartment_id,product_id)
      do update set quantity=inventory_stock_levels.quantity+excluded.quantity,
        updated_at=now();
    insert into inventory_stock_movements(reference,movement_type,product_id,
      apartment_id,quantity,unit_price,movement_date,note)
      values(v_reference,'transfer',v_line.product_id,v_request.apartment_id,
        v_line.quantity,v_line.unit_price,current_date,
        'Ticket '||v_request.reference||' · Invoice '||p_invoice_number);
  end loop;
  insert into inventory_invoices(request_id,invoice_number,invoice_date,
    storage_path,original_filename,mime_type,size_bytes,uploaded_by)
  values(p_request_id,trim(p_invoice_number),p_invoice_date,p_storage_path,
    p_original_filename,p_mime_type,p_size_bytes,auth.uid());
  update inventory_requests set status='fulfilled',
    invoice_reference=trim(p_invoice_number),fulfilled_at=now(),
    fulfilled_by=auth.uid() where id=p_request_id;
  return v_reference;
end $$;

grant select on public.inventory_invoices,
  public.inventory_invoice_register_view to authenticated;
grant execute on function public.inventory_fulfill_request(
  bigint,text,date,text,text,text,bigint) to authenticated;
