-- Two-role workflow: inventory admin and apartment user.

create table if not exists public.inventory_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('inventory_admin','apartment')),
  apartment_id bigint references public.inventory_apartments(id) on delete cascade,
  display_name text not null default '',
  created_at timestamptz not null default now(),
  check (
    (role='inventory_admin' and apartment_id is null) or
    (role='apartment' and apartment_id is not null)
  )
);

create table if not exists public.inventory_requests (
  id bigint generated by default as identity primary key,
  reference text not null unique default (
    'REQ-' || to_char(current_date,'YYYYMMDD') || '-'
    || upper(substr(md5(gen_random_uuid()::text),1,6))
  ),
  apartment_id bigint not null references public.inventory_apartments(id),
  requested_by uuid not null references auth.users(id),
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  note text not null default '',
  admin_note text not null default '',
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id)
);

create table if not exists public.inventory_request_lines (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.inventory_requests(id)
    on delete cascade,
  product_id bigint not null references public.inventory_products(id),
  quantity numeric(14,3) not null check (quantity > 0),
  unique(request_id,product_id)
);

create table if not exists public.inventory_usage (
  id bigint generated by default as identity primary key,
  apartment_id bigint not null references public.inventory_apartments(id),
  product_id bigint not null references public.inventory_products(id),
  quantity numeric(14,3) not null check (quantity > 0),
  usage_date date not null default current_date,
  note text not null default '',
  recorded_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists inventory_usage_month_idx
  on public.inventory_usage(apartment_id,usage_date desc);

alter table public.inventory_users enable row level security;
alter table public.inventory_requests enable row level security;
alter table public.inventory_request_lines enable row level security;
alter table public.inventory_usage enable row level security;

create or replace function public.inventory_is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from inventory_users
    where user_id=auth.uid() and role='inventory_admin')
$$;

drop policy if exists "users read self or admin" on public.inventory_users;
create policy "users read self or admin" on public.inventory_users for select
  to authenticated using (user_id=auth.uid() or inventory_is_admin());
drop policy if exists "requests read own apartment or admin" on public.inventory_requests;
create policy "requests read own apartment or admin" on public.inventory_requests
  for select to authenticated using (
    inventory_is_admin() or apartment_id=(
      select apartment_id from inventory_users where user_id=auth.uid()
    )
  );
drop policy if exists "request lines follow request access" on public.inventory_request_lines;
create policy "request lines follow request access" on public.inventory_request_lines
  for select to authenticated using (
    exists(select 1 from inventory_requests r where r.id=request_id)
  );
drop policy if exists "usage read own apartment or admin" on public.inventory_usage;
create policy "usage read own apartment or admin" on public.inventory_usage
  for select to authenticated using (
    inventory_is_admin() or apartment_id=(
      select apartment_id from inventory_users where user_id=auth.uid()
    )
  );

-- Remove the temporary no-login access.
drop policy if exists "inventory anon products" on public.inventory_products;
drop policy if exists "inventory anon apartments" on public.inventory_apartments;
drop policy if exists "inventory anon stock" on public.inventory_stock_levels;
drop policy if exists "inventory anon movements" on public.inventory_stock_movements;
revoke all on public.inventory_products,public.inventory_apartments,
  public.inventory_stock_levels,public.inventory_stock_movements from anon;
revoke all on public.inventory_products_view,public.inventory_apartments_view,
  public.inventory_apartment_stock_view,public.inventory_transfers_view,
  public.inventory_movement_log_view from anon;

create or replace function public.inventory_create_request(
  p_lines jsonb, p_note text default ''
) returns text
language plpgsql security definer set search_path=public as $$
declare v_apartment bigint; v_user uuid:=auth.uid(); v_request bigint;
  v_reference text; v_line jsonb; v_product bigint; v_qty numeric;
begin
  select apartment_id into v_apartment from inventory_users
    where user_id=v_user and role='apartment';
  if v_apartment is null then raise exception 'Apartment account not configured'; end if;
  if jsonb_array_length(p_lines)=0 then raise exception 'Add at least one item'; end if;
  insert into inventory_requests(apartment_id,requested_by,note)
    values(v_apartment,v_user,coalesce(p_note,''))
    returning id,reference into v_request,v_reference;
  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_product := (v_line->>'product_id')::bigint;
    v_qty := (v_line->>'quantity')::numeric;
    if v_qty<=0 then raise exception 'Quantity must be positive'; end if;
    insert into inventory_request_lines(request_id,product_id,quantity)
      values(v_request,v_product,v_qty);
  end loop;
  return v_reference;
end $$;

create or replace function public.inventory_review_request(
  p_request_id bigint, p_approve boolean, p_admin_note text default ''
) returns text
language plpgsql security definer set search_path=public as $$
declare v_request inventory_requests%rowtype; v_line record;
  v_available numeric; v_price numeric; v_name text;
  v_reference text := 'TR-' || to_char(current_date,'YYYYMMDD') || '-'
    || upper(substr(md5(gen_random_uuid()::text),1,6));
begin
  if not inventory_is_admin() then raise exception 'Admin access required'; end if;
  select * into v_request from inventory_requests where id=p_request_id for update;
  if not found then raise exception 'Request not found'; end if;
  if v_request.status<>'pending' then raise exception 'Request already reviewed'; end if;
  if not p_approve then
    update inventory_requests set status='rejected',admin_note=coalesce(p_admin_note,''),
      reviewed_at=now(),reviewed_by=auth.uid() where id=p_request_id;
    return v_request.reference;
  end if;
  for v_line in select rl.*,p.name,p.unit_price
    from inventory_request_lines rl join inventory_products p on p.id=rl.product_id
    where rl.request_id=p_request_id loop
    select quantity into v_available from inventory_stock_levels
      where location_type='warehouse' and product_id=v_line.product_id
      for update;
    if coalesce(v_available,0)<v_line.quantity then
      raise exception '% has only % available',v_line.name,coalesce(v_available,0);
    end if;
    update inventory_stock_levels set quantity=quantity-v_line.quantity,
      updated_at=now() where location_type='warehouse'
      and product_id=v_line.product_id;
    insert into inventory_stock_levels(location_type,apartment_id,product_id,quantity)
      values('apartment',v_request.apartment_id,v_line.product_id,v_line.quantity)
      on conflict(location_type,apartment_id,product_id)
      do update set quantity=inventory_stock_levels.quantity+excluded.quantity,
        updated_at=now();
    insert into inventory_stock_movements(reference,movement_type,product_id,
      apartment_id,quantity,unit_price,movement_date,note)
      values(v_reference,'transfer',v_line.product_id,v_request.apartment_id,
        v_line.quantity,v_line.unit_price,current_date,
        'Approved demand '||v_request.reference);
  end loop;
  update inventory_requests set status='approved',admin_note=coalesce(p_admin_note,''),
    reviewed_at=now(),reviewed_by=auth.uid() where id=p_request_id;
  return v_reference;
end $$;

create or replace function public.inventory_record_usage(
  p_product_id bigint,p_quantity numeric,p_usage_date date,p_note text default ''
) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_apartment bigint; v_available numeric; v_id bigint;
begin
  select apartment_id into v_apartment from inventory_users
    where user_id=auth.uid() and role='apartment';
  if v_apartment is null then raise exception 'Apartment account not configured'; end if;
  select quantity into v_available from inventory_stock_levels
    where location_type='apartment' and apartment_id=v_apartment
      and product_id=p_product_id for update;
  if coalesce(v_available,0)<p_quantity then raise exception 'Insufficient apartment stock'; end if;
  update inventory_stock_levels set quantity=quantity-p_quantity,updated_at=now()
    where location_type='apartment' and apartment_id=v_apartment
      and product_id=p_product_id;
  insert into inventory_usage(apartment_id,product_id,quantity,usage_date,note,recorded_by)
    values(v_apartment,p_product_id,p_quantity,coalesce(p_usage_date,current_date),
      coalesce(p_note,''),auth.uid()) returning id into v_id;
  return v_id;
end $$;

create or replace view public.inventory_request_summary_view
with (security_invoker=true) as
select r.id,r.reference,r.apartment_id,a.name apartment,r.status,r.note,
  r.admin_note,r.requested_at::text,r.reviewed_at::text,
  count(rl.id)::integer line_count,
  sum(rl.quantity)::double precision total_quantity,
  sum(rl.quantity*p.unit_price)::double precision total_value
from inventory_requests r join inventory_apartments a on a.id=r.apartment_id
join inventory_request_lines rl on rl.request_id=r.id
join inventory_products p on p.id=rl.product_id
group by r.id,a.name order by r.id desc;

create or replace view public.inventory_monthly_usage_view
with (security_invoker=true) as
select u.apartment_id,a.name apartment,
  date_trunc('month',u.usage_date)::date::text as "month",
  u.product_id,p.name product,p.unit,
  sum(u.quantity)::double precision quantity,
  sum(u.quantity*p.unit_price)::double precision value
from inventory_usage u join inventory_apartments a on a.id=u.apartment_id
join inventory_products p on p.id=u.product_id
group by u.apartment_id,a.name,date_trunc('month',u.usage_date),u.product_id,p.name,p.unit
order by "month" desc,a.name,p.name;

grant select on public.inventory_users,public.inventory_requests,
  public.inventory_request_lines,public.inventory_usage,
  public.inventory_request_summary_view,public.inventory_monthly_usage_view
  to authenticated;
grant execute on function public.inventory_is_admin(),
  public.inventory_create_request(jsonb,text),
  public.inventory_review_request(bigint,boolean,text),
  public.inventory_record_usage(bigint,numeric,date,text) to authenticated;
